added version 3.12 and 3.10

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -11,7 +11,7 @@ on:
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
-  TAG: "3.11"
+  TAG: 3.11 3.12 3.10
 
 jobs:
 
@@ -28,4 +28,12 @@ jobs:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Build and Push
-      run: docker buildx build -t "$REGISTRY/$IMAGE_NAME:$TAG" --push  -f Dockerfile .
+      run: |
+        for VERSION in ${{ env.VERSIONS }}; do
+          echo "Building and pushing image with python version: $VERSION"
+          docker buildx build --no-cache --build-arg NODE_VERSION=$VERSION -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$VERSION" --push -f Dockerfile .
+          if [ $? -ne 0 ]; then
+            echo "Error building or pushing image with version: $VERSION"
+            exit 1
+          fi
+        done
